export {default as MailAuth} from "./MailAuth" 
export {default as RestPassword} from "./RestPassord" 
export {default as Signin} from "./Signin" 
export {default as Signup} from "./Signup" 
export {default as PrivateRoute} from "./Private" 