export const SIGNING_REQUEST = 'SIGNING_REQUEST';
export const SIGNING_SUCCESS = 'SIGNING_SUCCESS';
export const SIGNING_FAILED = 'SIGNING_FAILED'; 

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED'; 