export {default as Kids} from "./Kids" 
export {default as Men} from "./Men" 
export {default as Women} from "./Women" 
export {default as Kitchen} from "./Kitchen" 
export {default as Profile} from "./Profile" 
export {default as Cart} from "./Cart" 
export {default as Home} from "./Home" 
export {default as SingleProduct} from "./SingleProduct"